version: '3.8'
services:
  db:
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: contacorrente
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3308:3306
    expose:
      - 3306
    networks:
      - contacorrente-network
  contacorrente:
    restart: always
    build: ./ContaCorrente
    working_dir: /ContaCorrente
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/contacorrente?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 3003:3003
    command: mnv spring-boot:run
    depends_on:
      - db
    networks:
      - contacorrente-network
networks:
  contacorrente-network:
    driver: bridge